sudo: required
services:
  - docker 

before_install:
  - docker build -t shonphand/react-test -f ./client/Dockerfile.dev ./client

scripts:
  - docker run -e CI=true shonphand/react-test npm test

after_success:
  - docker build -t shonphand/multi-client ./client
  - docker build -t shonphand/multi-nginx ./nginx
  - docker build -t shonphand/multi-server ./server
  - docker build -t shonphand/multi-worker ./worker
  #Login to dockerhub
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # take above images and push to dockerhub
  - docker push shonphand/multi-client
  - docker push shonphand/multi-nginx
  - docker push shonphand/multi-server
  - docker push shonphand/multi-worker

